require("config")

-- :wq automatically creates needed directories
vim.api.nvim_create_autocmd("BufWritePre", {
	pattern = "*",
	callback = function()
		local dir = vim.fn.expand("<afile>:p:h")
		if vim.fn.isdirectory(dir) == 0 then
			vim.fn.mkdir(dir, "p")
		end
	end,
})

-- WARNING: generated by chatgpt
-- automatically check if the file is modified to avoid incorrectly marking it as modified
local function check_file_changed()
	-- Check if the buffer is a regular file
	if vim.bo.buftype ~= "" or not vim.bo.modifiable then
		return
	end

	-- Check if the buffer has been modified
	if not vim.bo.modified then
		return
	end

	local current_lines = vim.api.nvim_buf_get_lines(0, 0, -1, true)
	local original_lines = vim.fn.readfile(vim.fn.expand("%"))

	if vim.deep_equal(current_lines, original_lines) then
		vim.bo.modified = false
	end
end

vim.api.nvim_create_autocmd({ "TextChanged", "TextChangedI" }, {
	callback = check_file_changed,
	group = vim.api.nvim_create_augroup("CheckIfModified", { clear = true }),
})
